### PR TITLE
NGPOC-184: Under user default properties it should display selected location of user

### PR DESCRIPTION
**Pull request by ExaMind**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
     
     Fixes the NGPOC-184 issue.

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

### CODE REVIEW

**Comment by ExaMind** [comment]
@enyachoke I see that you need the commit message to be more descriptive from the @tjlundstrom NGPOC-185 pull request. Do you need me to change my commit message?

I can change it if you need me to. Let me know.

**Comment by ExaMind** [comment]
@enyachoke I see that you need the commit message to be more descriptive from the @tjlundstrom NGPOC-185 pull request. Do you need me to change my commit message?

I can change it if you need me to. Let me know.

**Comment by enyachoke** [comment]
Yeah please do.

**Comment by ExaMind** [comment]
@enyachoke I changed the commit message.

**Pull request merged**
